#!/bin/sh
#  ____     _ 
# |  _ \   | |
# | |_) |  | |
# |  __/ |_| |
# |_|   \___/ 
#             

c='•'

distro="debian"

case ${distro} in
	debian)
		pkgs="apt search "
		;;
	arch)
		pkgs="pacman -Ss "
		;;
	void)
		pkgs="xbps-query -Rs "
		;;
	redhat)
		pkgs="dnf search "
		;;
	suse)
		pkgs="zypper search "
		;;
	*)
		pkgs=
		;;
esac

tmp() {
cat << EOF
	${SHELL}
	${pkgs}
	sudo sv restart 
	iwctl station list 
	pulsemixer
	xprop
	btop
EOF
}

term="st -t st"
sh="bash"
prompt='st-exec'

pached=$(dmenu -v | grep -c 'hos-patched')
if [ ${pached} -eq 1 ]; then
	patches="-c -bw 2 -g 1 -r"
fi

runner="dmenu -p ${prompt} -l 15 ${patches} ${@}"

#${sh} -c \
#	"$(tmp | sed -e "s/^/${c} /" -e 's/\t/ /g' \
#		| ${runner} | sed "s/^${c} //")"

cmd=$(tmp | sed -e "s/^/${c} /" -e 's/\t/ /g' | ${runner} | sed "s/^${c} //")

${term} \
	${sh} -c "sleep 1; ${cmd} && ${sh}" \
