#!/bin/sh

# This script is the SUDO_ASKPASS variable, meaning that it will be used as a
# password prompt if needed.

#dmenu -P -p "${1}" </dev/null

if [ -z ${DISPLAY} ]; then
	stty -echo
	read -p "${1}" PASS
	echo $PASS
	unset PASS
	stty echo
else
	dmenu -P -p "$1" <&- && echo
fi
