#!/bin/sh

# This script is the SUDO_ASKPASS variable, meaning that it will be used as a
# password prompt if needed.

tmp="${1}"
dmenu -fn 'Ubuntu Mono:size=16' -P -p "${tmp}" </dev/null

# if [ -z ${DISPLAY} ]; then
# 	stty -echo
# 	read -p "${1}" PASS
# 	echo $PASS
# 	unset PASS
# 	stty echo
# else
# 	dmenu -P -p "$1" <&- && echo
# fi
