#!/bin/sh
#  ____     _ 
# |  _ \   | |
# | |_) |  | |
# |  __/ |_| |
# |_|   \___/ 
#             

## varaibles {{{
#path="${HOME}/.local/hos/chars/emoji.txt"
#prompt=$(echo ${0} | awk -F '/' '{print $NF;}')
#patched="-bw 0 -g 4 -l 10"
#style=""
#eargs=""
## }}}
## help function {{{
#help() {
#cat << EOF
#${prompt}: select and copy emojies to clipboard
#
#usage: [-h] [-s style] [-e extra_args]
#
#	long format arguemts:
#	    --style      <style>
#	    --extra      <extra-arguemts>
#	    --help       print this message
#
#	style:
#	    • gui        use “dmenu” as run launcher (default)
#	    • tui        use “fzf” instead
#
#	extra:
#	    • specify extra arguments to the run launcher (dmenu or fzf)
#
#	running without any arguments:
#	    • the default behavior of the script is to use dmenu as default launcher
#
#EOF
#}
## }}}
## argument parsing {{{
#while [ "${#}" -gt 0 ]; do
#	case ${1} in
#		-s|--style)
#			style="${2}"
#			shift
#			;;
#		-e|--extra)
#			eargs="${2}"
#			shift
#			;;
#		-h|--help)
#			help
#			exit 0
#			;;
#		*)
#			echo "Unknown parameter passed: ${1}"
#			exit 1
#			;;
#	esac
#	shift
#done
## }}}

mpv --profile=low-latency --untimed /dev/video0
