#!/bin/sh
#  ____     _ 
# |  _ \   | |
# | |_) |  | |
# |  __/ |_| |
# |_|   \___/ 
#             

#	$(jdate '+%W' | awk '{print substr($0, 3)}' | sed 's,/,,g') \
printf '%s %s %s %s' \
	$(jdate '+%m/%d') \
	$(date '+%a %y-%m-%d %H:%M')
#	$(jdate '+%E') \

