#!/bin/sh
#  ____     _ 
# |  _ \   | |
# | |_) |  | |
# |  __/ |_| |
# |_|   \___/ 
#             

set -e

null=♦

if [ -z ${1} ]; then
	dev=enp46s0
else
	dev=$1
fi

lip=$(ip a \
	| grep ${dev} \
	| grep 'inet ' \
	| awk '{print $2;}' \
	| awk -F '/' '{print $1;}')

[ -z $lip ] && lip=$null

printf "${lip}"
