#!/bin/sh
#  ____     _ 
# |  _ \   | |
# | |_) |  | |
# |  __/ |_| |
# |_|   \___/ 
#             

defpicdir="${HOME}/pic"
presist_wall="${defpicdir}/.wall"
#script_name=$(echo ${0} | awk -F '/' '{print $NF;}')
script_name="Wallpaper"
runner="xwallpaper --no-randr --zoom"
pached=$(dmenu -v | grep -c 'hos-patched')
if [ ${pached} -eq 1 ]; then
	patches='-c -g 1 -bw 2'
fi
menu="dmenu -l 20 -p ${script_name} ${patches}"
viewer="nsxiv -tor"
viewe="nsxiv -to"

help() {
cat << EOF
usage: ${script_name} [img] [dir] [-s <dir>] [-h] []
	-r             rerun the xwallpaper command
	-h             print this message
	-s <dir>       random pic from <dir> as wallpaper
	<img>          set the image as wallpaper
	<dir>          show all the pictures from directory to choose from
	<no args>      choose a picture from "${defpicdir}"
EOF
}

notif_send() {
	if [ ${?} -eq 0 ]; then
		notify-send -u normal -a ${script_name} -i background "${1}" "${2}"
	fi
}

shuf_wall() {
	thewall=$(ls "${1}"/*.{jpg,png} | shuf | head -1)
	${runner} "${thewall}"
	cp -f "${thewall}" ${presist_wall}
	ww="$(echo "${thewall}" | awk -F '/' '{print $NF;}')"
	if [ $? -eq 0 ]; then
		notif_send "Wallpaper changed" "${ww}"
		exit 0
	else
		exit 1
	fi
}

dir_wall() {
	thewall=$(${viewer} "${1}")
	if [ -f "${thewall}" ]; then
		${runner} "${thewall}"
		cp -f "${thewall}" ${presist_wall}
		ww="$(echo "${thewall}" | awk -F '/' '{print $NF;}')"
		if [ $? -eq 0 ]; then
			notif_send "Wallpaper changed" "${ww}"
			exit 0
		else
			exit 1
		fi
	fi
}

set_wall() {
	ww="$(echo "${1}" | awk -F '/' '{print $NF;}')"
	if [ -n "${ww}" ]; then
		${runner} "${1}"
		cp -f "${1}" ${presist_wall}
		notif_send "Wallpaper changed" "${ww}"
		exit 0
	else
		exit 1
	fi
}

dir_wall_intractive() {
	thewall=$(${viewer} "${1}")
	if [ -f "${thewall}" ]; then
		${runner} "${thewall}"
		if [ $? -eq 0 ]; then
			cp -f "${thewall}" ${presist_wall}
			ww="$(echo "${thewall}" | awk -F '/' '{print $NF;}')"
			notif_send "Wallpaper changed" "${ww}"
			exit 0
		else
			exit 1
		fi
	elif [ -z "${thewall}" ]; then
		choose_wall
	fi
}

choose_wall() {
	locwalldir="${defpicdir}/wall"
	selected_dir="$(find ${locwalldir} -maxdepth 1 -type d \
		| awk -F '/' '{print $NF;}' \
		| sed 's/wall$/./' \
		| ${menu})"
	if [ "${locwalldir}/${selected_dir}" = "${locwalldir}/" ]; then
		exit 2
	else
		dir_wall_intractive "${locwalldir}/${selected_dir}"
	fi
#	set_wall "${wall}"
}

#if [ "${1}" = '-h' ]; then
#	help
#	exit 0
#elif [ "${1}" = '-s' ]; then
#	shuf_wall "${2}"
#elif [ "${1}" = '-r' ]; then
#	${runner} ${presist_wall}
#elif [ -d "${1}" ]; then
#	dir_wall ${1}
#elif [ -f "${1}" ]; then
#	set_wall "${1}"
#else
#	choose_wall
#fi

case "${1}" in
	-h) help; exit 0 ;;
	-s) shuf_wall "${2}" ;;
	-r) ${runner} ${presist_wall} ;;
	-d) dir_wall "${1}" ;;
	-f) set_wall "${1}" ;;
	*) choose_wall ;;
esac
